import pandas as pd
import numpy as np

# Excelファイルの読み込み
df = pd.read_excel('./work/data/raw/購買データ_商品属性付き.xlsx')

# 得意先コードと商品名の列を抽出
subset_df = df[['受注日', '得意先コード', '商品名', '製品区分', 'サイズ・規格']]
# '受注日'列が日付以外の値を含む行を除外
subset_df = subset_df[subset_df['受注日'].astype(str).str.match(r'\d{8}')]
# '受注日'列を日付型に変換
subset_df['受注日'] = pd.to_datetime(subset_df['受注日'], format='%Y%m%d')
# サイズ・規格の中に「封筒」という文字列が含まれるデータを抽出
filtered_df = subset_df[subset_df['サイズ・規格'].str.contains('封筒')]
# '受注日'が2019-01-07以降のデータに絞り込み
filtered_df = filtered_df[filtered_df['受注日'] >= '2019-01-07']

# # 新しいExcelファイルとして保存
# file_path = '封筒.xlsx'
# filtered_df.to_excel(file_path, index=False)


# 'サイズ・規格' 列のユニークな値とその出現回数を取得
size_counts = filtered_df['サイズ・規格'].value_counts().reset_index().rename(columns={'index': 'サイズ・規格', 'サイズ・規格': '回数'})
# # 新しいExcelファイルとして保存
# file_path = '属性.xlsx'
# size_counts.to_excel(file_path, index=False)


# 封筒.xlsxの読み込み
df = pd.read_excel('封筒.xlsx')
# 得意先ごとの購入回数を数える
purchase_counts = df['得意先コード'].value_counts()
# 購入回数が2回以上の得意先コードを取得
selected_customers = purchase_counts[purchase_counts >= 2].index
# 購入回数が2回以上の得意先のデータを抽出
filtered_df = df[df['得意先コード'].isin(selected_customers)]
# # 新しいExcelファイルとして保存
# filtered_df.to_csv('顧客.csv', index=False, encoding='utf-8')


# 顧客.csvの読み込み
df = pd.read_csv('顧客.csv', encoding='utf-8')
# # 'サイズ・規格' 列のユニークな値を取得
# size_types = df['サイズ・規格'].unique()
# # 結果を表示
# print(size_types)

#結果用データフレーム
result_df = pd.DataFrame()
result_df['得意先コード'] = df[['得意先コード']]

result_df['角封筒_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                            &df['サイズ・規格'].str.contains('封筒')
                            &df['製品区分'].str.contains('オーダーメイド')
                            &~df['サイズ・規格'].str.contains('窓明')
                            &~df['サイズ・規格'].str.contains('アドヘア')
                            &~df['サイズ・規格'].str.contains('テープ')
                            &~df['サイズ・規格'].str.contains('ホットメルト')
                            ).astype(int)
result_df['角封筒_既製品'] = (df['サイズ・規格'].str.contains('角')
                            &df['サイズ・規格'].str.contains('封筒')
                            &df['製品区分'].str.contains('既製品')
                            &~df['サイズ・規格'].str.contains('窓明')
                            &~df['サイズ・規格'].str.contains('アドヘア')
                            &~df['サイズ・規格'].str.contains('テープ')
                            &~df['サイズ・規格'].str.contains('ホットメルト')
                            ).astype(int)

result_df['角封筒(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('アドヘア')
                                    &df['製品区分'].str.contains('オーダーメイド')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)
result_df['角封筒(アドヘア)_既製品'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('アドヘア')
                                    &df['製品区分'].str.contains('既製品')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)

result_df['角封筒(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('テープ')
                                    &df['製品区分'].str.contains('オーダーメイド')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)
result_df['角封筒(テープ付)_既製品'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('テープ')
                                    &df['製品区分'].str.contains('既製品')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)

result_df['角封筒(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('オーダーメイド')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)
result_df['角封筒(ホットメルト)_既製品'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('既製品')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)

result_df['角窓明封筒_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('窓明封筒')
                                    &~df['サイズ・規格'].str.contains('アドヘア')
                                    &~df['サイズ・規格'].str.contains('テープ')
                                    &~df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
result_df['角窓明封筒_既製品'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('窓明封筒')
                                    &~df['サイズ・規格'].str.contains('アドヘア')
                                    &~df['サイズ・規格'].str.contains('テープ')
                                    &~df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('既製品')).astype(int)

result_df['角窓明封筒(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('アドヘア')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
# result_df['角窓明封筒(アドヘア)_既製品'] = (df['サイズ・規格'].str.contains('角')
#                                     &df['サイズ・規格'].str.contains('封筒')
#                                     &df['サイズ・規格'].str.contains('アドヘア')
#                                     &df['製品区分'].str.contains('既製品')).astype(int)

result_df['角窓明封筒(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('テープ')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
# result_df['角窓明封筒(テープ付)_既製品'] = (df['サイズ・規格'].str.contains('角')
#                                     &df['サイズ・規格'].str.contains('封筒')
#                                     &df['サイズ・規格'].str.contains('テープ')
#                                     &df['製品区分'].str.contains('既製品')).astype(int)

result_df['角窓明封筒(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('角')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
# result_df['角窓明封筒(ホットメルト)_既製品'] = (df['サイズ・規格'].str.contains('角')
#                                     &df['サイズ・規格'].str.contains('封筒')
#                                     &df['サイズ・規格'].str.contains('ホットメルト')
#                                     &df['製品区分'].str.contains('既製品')).astype(int)

result_df['長封筒_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                            &df['サイズ・規格'].str.contains('封筒')
                            &df['製品区分'].str.contains('オーダーメイド')
                            &~df['サイズ・規格'].str.contains('窓明')
                            &~df['サイズ・規格'].str.contains('アドヘア')
                            &~df['サイズ・規格'].str.contains('テープ')
                            &~df['サイズ・規格'].str.contains('ホットメルト')
                            ).astype(int)
result_df['長封筒_既製品'] = (df['サイズ・規格'].str.contains('長')
                            &df['サイズ・規格'].str.contains('封筒')
                            &df['製品区分'].str.contains('既製品')
                            &~df['サイズ・規格'].str.contains('窓明')
                            &~df['サイズ・規格'].str.contains('アドヘア')
                            &~df['サイズ・規格'].str.contains('テープ')
                            &~df['サイズ・規格'].str.contains('ホットメルト')
                            ).astype(int)

result_df['長封筒(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('アドヘア')
                                    &df['製品区分'].str.contains('オーダーメイド')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)
# result_df['長封筒(アドヘア)_既製品'] = (df['サイズ・規格'].str.contains('長')
#                                     &df['サイズ・規格'].str.contains('封筒')
#                                     &df['サイズ・規格'].str.contains('アドヘア')
#                                     &df['製品区分'].str.contains('既製品')
#                                     &~df['サイズ・規格'].str.contains('窓明')).astype(int)

result_df['長封筒(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('テープ')
                                    &df['製品区分'].str.contains('オーダーメイド')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)
result_df['長封筒(テープ付)_既製品'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('テープ')
                                    &df['製品区分'].str.contains('既製品')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)

result_df['長封筒(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('オーダーメイド')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)
result_df['長封筒(ホットメルト)_既製品'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('既製品')
                                    &~df['サイズ・規格'].str.contains('窓明')).astype(int)

result_df['長窓明封筒_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('窓明封筒')
                                    &~df['サイズ・規格'].str.contains('アドヘア')
                                    &~df['サイズ・規格'].str.contains('テープ')
                                    &~df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
result_df['長窓明封筒_既製品'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('窓明封筒')
                                    &~df['サイズ・規格'].str.contains('アドヘア')
                                    &~df['サイズ・規格'].str.contains('テープ')
                                    &~df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('既製品')).astype(int)

result_df['長窓明封筒(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('アドヘア')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
# result_df['長窓明封筒(アドヘア)_既製品'] = (df['サイズ・規格'].str.contains('長')
#                                     &df['サイズ・規格'].str.contains('封筒')
#                                     &df['サイズ・規格'].str.contains('アドヘア')
#                                     &df['製品区分'].str.contains('既製品')).astype(int)

result_df['長窓明封筒(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('テープ')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
# result_df['長窓明封筒(テープ付)_既製品'] = (df['サイズ・規格'].str.contains('長')
#                                     &df['サイズ・規格'].str.contains('封筒')
#                                     &df['サイズ・規格'].str.contains('テープ')
#                                     &df['製品区分'].str.contains('既製品')).astype(int)

result_df['長窓明封筒(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('長')
                                    &df['サイズ・規格'].str.contains('封筒')
                                    &df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('オーダーメイド')).astype(int)
# result_df['長窓明封筒(ホットメルト)_既製品'] = (df['サイズ・規格'].str.contains('長')
#                                     &df['サイズ・規格'].str.contains('封筒')
#                                     &df['サイズ・規格'].str.contains('ホットメルト')
#                                     &df['製品区分'].str.contains('既製品')).astype(int)


result_df['洋封筒(テープ付)_既製品'] = (df['サイズ・規格'].str.contains('洋封筒')
                                    &df['サイズ・規格'].str.contains('テープ')
                                    &df['製品区分'].str.contains('既製品')).astype(int)
result_df['洋封筒(ホットメルト)_既製品'] = (df['サイズ・規格'].str.contains('洋封筒')
                                    &df['サイズ・規格'].str.contains('ホットメルト')
                                    &df['製品区分'].str.contains('既製品')).astype(int)

result_df['封筒_オーダーメイド'] = (df['サイズ・規格'].str.contains('封筒')
                           &df['製品区分'].str.contains('オーダーメイド')
                           &~df['サイズ・規格'].str.contains('角')
                           &~df['サイズ・規格'].str.contains('長')
                           &~df['サイズ・規格'].str.contains('叺|かます')
                           &~df['サイズ・規格'].str.contains('ダイヤモンド')
                           &~df['サイズ・規格'].str.contains('窓明')
                           ).astype(int)
# result_df['封筒_既製品'] = (df['サイズ・規格'].str.contains('封筒')
#                            &df['製品区分'].str.contains('既製品')
#                            &~df['サイズ・規格'].str.contains('角')
#                            &~df['サイズ・規格'].str.contains('長')
#                            &~df['サイズ・規格'].str.contains('叺|かます')
#                            &~df['サイズ・規格'].str.contains('ダイヤモンド')
#                            &~df['サイズ・規格'].str.contains('窓明')
#                            ).astype(int)
result_df['封筒(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('封筒')
                                &df['サイズ・規格'].str.contains('アドヘア')
                                &df['製品区分'].str.contains('オーダーメイド')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺|かます')
                                &~df['サイズ・規格'].str.contains('ダイヤモンド')
                                &~df['サイズ・規格'].str.contains('窓明')
                                ).astype(int)
result_df['封筒(アドヘア)_既製品'] = (df['サイズ・規格'].str.contains('封筒')
                                &df['サイズ・規格'].str.contains('アドヘア')
                                &df['製品区分'].str.contains('既製品')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺|かます')
                                &~df['サイズ・規格'].str.contains('ダイヤモンド')
                                &~df['サイズ・規格'].str.contains('窓明')
                                ).astype(int)
result_df['封筒(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('封筒')
                                &df['サイズ・規格'].str.contains('テープ付')
                                &df['製品区分'].str.contains('オーダーメイド')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺|かます')
                                &~df['サイズ・規格'].str.contains('ダイヤモンド')
                                &~df['サイズ・規格'].str.contains('窓明')
                                ).astype(int)
result_df['封筒(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('封筒')
                                 &df['サイズ・規格'].str.contains('ホットメルト')
                                &df['製品区分'].str.contains('オーダーメイド')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺|かます')
                                &~df['サイズ・規格'].str.contains('ダイヤモンド')
                                &~df['サイズ・規格'].str.contains('窓明')
                                ).astype(int)

result_df['開封封筒_オーダーメイド'] = df['サイズ・規格'].str.contains('開封').astype(int)
result_df['甘栗封筒_オーダーメイド'] = df['サイズ・規格'].str.contains('甘栗').astype(int)
result_df['レントゲン封筒_オーダーメイド'] = df['サイズ・規格'].str.contains('レントゲン').astype(int)

result_df['窓明封筒_オーダーメイド'] = (df['サイズ・規格'].str.contains('窓明')
                                &df['製品区分'].str.contains('オーダーメイド')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺')
                                &~df['サイズ・規格'].str.contains('アドヘア')
                                &~df['サイズ・規格'].str.contains('テープ')
                                &~df['サイズ・規格'].str.contains('ホットメルト')
                                ).astype(int)
result_df['窓明封筒_既製品'] = (df['サイズ・規格'].str.contains('窓明')
                                &df['製品区分'].str.contains('既製品')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺')
                                &~df['サイズ・規格'].str.contains('アドヘア')
                                &~df['サイズ・規格'].str.contains('テープ')
                                &~df['サイズ・規格'].str.contains('ホットメルト')
                                ).astype(int)
result_df['窓明(アドヘア)封筒_オーダーメイド'] = (df['サイズ・規格'].str.contains('窓明')
                                &df['サイズ・規格'].str.contains('アドヘア')
                                &df['製品区分'].str.contains('オーダーメイド')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺')
                                ).astype(int)
result_df['窓明(アドヘア)封筒_既製品'] = (df['サイズ・規格'].str.contains('窓明')
                                &df['サイズ・規格'].str.contains('アドヘア')
                                &df['製品区分'].str.contains('既製品')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺')
                                ).astype(int)
result_df['窓明封筒(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('窓明')
                                &df['サイズ・規格'].str.contains('テープ付')
                                &df['製品区分'].str.contains('オーダーメイド')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺')
                                ).astype(int)
result_df['窓明封筒(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('窓明')
                                &df['サイズ・規格'].str.contains('ホットメルト')
                                &df['製品区分'].str.contains('オーダーメイド')
                                &~df['サイズ・規格'].str.contains('角')
                                &~df['サイズ・規格'].str.contains('長')
                                &~df['サイズ・規格'].str.contains('叺')
                                ).astype(int)
result_df['手貼り_オーダーメイド'] = df['サイズ・規格'].str.contains('手貼り').astype(int)
result_df['ダイヤモンド貼_オーダーメイド'] = (df['サイズ・規格'].str.contains('ダイヤモンド')
                                &df['製品区分'].str.contains('オーダーメイド')).astype(int)
result_df['ダイヤモンド貼_既製品'] = (df['サイズ・規格'].str.contains('ダイヤモンド')
                            &df['製品区分'].str.contains('既製品')).astype(int)
result_df['ダイヤモンド貼(アラビア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('ダイヤモンド')
                                   &df['サイズ・規格'].str.contains('アラビア')).astype(int)
result_df['内叺_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼封筒')
                           &df['製品区分'].str.contains('オーダーメイド')
                           &~df['サイズ・規格'].str.contains('窓明')
                           &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼封筒')
                                 &df['サイズ・規格'].str.contains('アドヘア')
                           &df['製品区分'].str.contains('オーダーメイド')
                           &~df['サイズ・規格'].str.contains('窓明')
                           &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼封筒')
                                 &df['サイズ・規格'].str.contains('テープ付')
                           &df['製品区分'].str.contains('オーダーメイド')
                           &~df['サイズ・規格'].str.contains('窓明')
                           &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼封筒')
                                 &df['サイズ・規格'].str.contains('ホットメルト')
                           &df['製品区分'].str.contains('オーダーメイド')
                           &~df['サイズ・規格'].str.contains('窓明')
                           &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺(アラビア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼封筒')
                                 &df['サイズ・規格'].str.contains('アラビア')
                           &df['製品区分'].str.contains('オーダーメイド')
                           &~df['サイズ・規格'].str.contains('窓明')
                           &~df['サイズ・規格'].str.contains('大内')).astype(int)

result_df['内叺窓明_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                             &~df['サイズ・規格'].str.contains('大内')).astype(int)
# result_df['内叺窓明_既製品'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
#                             &df['製品区分'].str.contains('既製品')
#                             &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('アドヘア')
                                   &df['製品区分'].str.contains('オーダーメイド')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(アドヘア)_既製品'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('アドヘア')
                                   &df['製品区分'].str.contains('既製品')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(テープ付)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('テープ付')
                                   &df['製品区分'].str.contains('オーダーメイド')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(テープ付)_既製品'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('テープ付')
                                   &df['製品区分'].str.contains('既製品')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(ホットメルト)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('ホットメルト')
                                   &df['製品区分'].str.contains('オーダーメイド')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(ホットメルト)_既製品'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('ホットメルト')
                                   &df['製品区分'].str.contains('既製品')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(アラビア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('アラビア')
                                   &df['製品区分'].str.contains('オーダーメイド')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['内叺窓明(アラビア)_既製品'] = (df['サイズ・規格'].str.contains('内叺貼窓明')
                                   &df['サイズ・規格'].str.contains('アラビア')
                                   &df['製品区分'].str.contains('既製品')
                                   &~df['サイズ・規格'].str.contains('大内')).astype(int)
result_df['大内叺_オーダーメイド'] = (df['サイズ・規格'].str.contains('大内叺貼')
                           &df['製品区分'].str.contains('オーダーメイド')).astype(int)
result_df['大内叺(アドヘア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('大内叺貼封筒\(アドヘア\)')
                                &~df['サイズ・規格'].str.contains('窓明')).astype(int)
result_df['大内叺(アラビア)_オーダーメイド'] = (df['サイズ・規格'].str.contains('大内叺貼封筒\(アラビア\)')
                                &~df['サイズ・規格'].str.contains('窓明')).astype(int)
result_df['大内叺窓明_オーダーメイド'] = df['サイズ・規格'].str.contains('大内叺貼窓明').astype(int)
result_df['大内叺窓明(アドヘア)_オーダーメイド'] = df['サイズ・規格'].str.contains('大内叺貼窓明封筒\(アドヘア\)').astype(int)
result_df['大内叺窓明(アラビア)_オーダーメイド'] = df['サイズ・規格'].str.contains('大内叺貼窓明封筒\(アラビア\)').astype(int)
result_df['ガゼット_オーダーメイド'] = df['サイズ・規格'].str.contains('ガゼット').astype(int)




result_df['S貼'] = df['商品名'].str.contains('Ｓ貼').astype(int)
result_df['C貼'] = df['商品名'].str.contains('Ｃ貼').astype(int)
result_df['逆S'] = df['商品名'].str.contains('逆Ｓ貼').astype(int) #逆S貼
# IDごとに集計
result_df = result_df.groupby('得意先コード').sum().reset_index()

# 購買回数を log10(x + 1) で変換
purchase_columns = result_df.columns[1:]  # '得意先コード'以外の列を選択
result_df[purchase_columns] = np.log10(result_df[purchase_columns] + 1)
result_df.to_csv('./work/自分/自分log.csv', index=False, encoding='utf-8')
print(result_df)